name: rama
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: clone the code
      uses: actions/checkoput@v4

    - name: print indec.html
      run:  cat index.html
      
         
    
